import type { Metadata } from "next";
import "./globals.css";
import { Rethink_Sans } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ClerkAuthProvider from "@/components/providers/clerk-auth-provider";

const font = Rethink_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkAuthProvider>
      <html lang='en'>
        <body className={`${font.className} antialiased`}>
          <Navbar />
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkAuthProvider>
  );
}
